name: tasks
'on':
  push:
    branches:
      - dist
jobs:
  prepare:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.POD_DATA_GEN }}
      - name: prep
        run: |
          mkdir temp
          touch temp/sth.txt
          git add temp
          git commit -m "Create temp folder"
          git push origin dist
  group-0:
    runs-on: macos-latest
    needs:
      - prepare
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - name: Checkout ğŸ§
        uses: actions/checkout@v2
      - name: Download & Cache Stanford CoreNLP ğŸ‹ï¸
        run: >
          wget -P tmp
          "https://downloads.cs.stanford.edu/nlp/software/stanford-ner-4.2.0.zip"

          unzip tmp/stanford-ner-4.2.0.zip -d tmp/
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.POD_DATA_GEN }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npx tsc
          mkdir temp
          touch temp/something.txt
      - name: Process w/ Name Entity Recognition ğŸ¤–
        run: |
          mkdir temp/podcasts_palettes_ner-0
          node --max-old-space-size=10240 out/lib/ner.js 0 68 0
      - name: Cache Output of the Job
        id: podcasts_palettes_ner-0
        uses: actions/cache@v2
        with:
          path: temp/podcasts_palettes_ner-0
          key: podcasts_palettes_ner-0
      - name: commit & Push changes ğŸ’¾
        run: |
          # Stage the file, commit and push
          git pull
          git add temp/podcasts_palettes_ner-0
          git commit -m "updated podcast group-0"
          git push origin dist
  group-1:
    runs-on: macos-latest
    needs:
      - prepare
      - group-0
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - name: Checkout ğŸ§
        uses: actions/checkout@v2
      - name: Download & Cache Stanford CoreNLP ğŸ‹ï¸
        run: >
          wget -P tmp
          "https://downloads.cs.stanford.edu/nlp/software/stanford-ner-4.2.0.zip"

          unzip tmp/stanford-ner-4.2.0.zip -d tmp/
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.POD_DATA_GEN }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npx tsc
          mkdir temp
          touch temp/something.txt
      - name: Process w/ Name Entity Recognition ğŸ¤–
        run: |
          mkdir temp/podcasts_palettes_ner-1
          node --max-old-space-size=10240 out/lib/ner.js 68 136 1
      - name: Cache Output of the Job
        id: podcasts_palettes_ner-1
        uses: actions/cache@v2
        with:
          path: temp/podcasts_palettes_ner-1
          key: podcasts_palettes_ner-1
      - name: commit & Push changes ğŸ’¾
        run: |
          # Stage the file, commit and push
          git pull
          git add temp/podcasts_palettes_ner-1
          git commit -m "updated podcast group-1"
          git push origin dist
  group-2:
    runs-on: macos-latest
    needs:
      - prepare
      - group-0
      - group-1
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - name: Checkout ğŸ§
        uses: actions/checkout@v2
      - name: Download & Cache Stanford CoreNLP ğŸ‹ï¸
        run: >
          wget -P tmp
          "https://downloads.cs.stanford.edu/nlp/software/stanford-ner-4.2.0.zip"

          unzip tmp/stanford-ner-4.2.0.zip -d tmp/
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.POD_DATA_GEN }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npx tsc
          mkdir temp
          touch temp/something.txt
      - name: Process w/ Name Entity Recognition ğŸ¤–
        run: |
          mkdir temp/podcasts_palettes_ner-2
          node --max-old-space-size=10240 out/lib/ner.js 136 204 2
      - name: Cache Output of the Job
        id: podcasts_palettes_ner-2
        uses: actions/cache@v2
        with:
          path: temp/podcasts_palettes_ner-2
          key: podcasts_palettes_ner-2
      - name: commit & Push changes ğŸ’¾
        run: |
          # Stage the file, commit and push
          git pull
          git add temp/podcasts_palettes_ner-2
          git commit -m "updated podcast group-2"
          git push origin dist
  group-3:
    runs-on: macos-latest
    needs:
      - prepare
      - group-0
      - group-1
      - group-2
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - name: Checkout ğŸ§
        uses: actions/checkout@v2
      - name: Download & Cache Stanford CoreNLP ğŸ‹ï¸
        run: >
          wget -P tmp
          "https://downloads.cs.stanford.edu/nlp/software/stanford-ner-4.2.0.zip"

          unzip tmp/stanford-ner-4.2.0.zip -d tmp/
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.POD_DATA_GEN }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npx tsc
          mkdir temp
          touch temp/something.txt
      - name: Process w/ Name Entity Recognition ğŸ¤–
        run: |
          mkdir temp/podcasts_palettes_ner-3
          node --max-old-space-size=10240 out/lib/ner.js 204 272 3
      - name: Cache Output of the Job
        id: podcasts_palettes_ner-3
        uses: actions/cache@v2
        with:
          path: temp/podcasts_palettes_ner-3
          key: podcasts_palettes_ner-3
      - name: commit & Push changes ğŸ’¾
        run: |
          # Stage the file, commit and push
          git pull
          git add temp/podcasts_palettes_ner-3
          git commit -m "updated podcast group-3"
          git push origin dist
  group-4:
    runs-on: macos-latest
    needs:
      - prepare
      - group-0
      - group-1
      - group-2
      - group-3
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - name: Checkout ğŸ§
        uses: actions/checkout@v2
      - name: Download & Cache Stanford CoreNLP ğŸ‹ï¸
        run: >
          wget -P tmp
          "https://downloads.cs.stanford.edu/nlp/software/stanford-ner-4.2.0.zip"

          unzip tmp/stanford-ner-4.2.0.zip -d tmp/
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.POD_DATA_GEN }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npx tsc
          mkdir temp
          touch temp/something.txt
      - name: Process w/ Name Entity Recognition ğŸ¤–
        run: |
          mkdir temp/podcasts_palettes_ner-4
          node --max-old-space-size=10240 out/lib/ner.js 272 342 4
      - name: Cache Output of the Job
        id: podcasts_palettes_ner-4
        uses: actions/cache@v2
        with:
          path: temp/podcasts_palettes_ner-4
          key: podcasts_palettes_ner-4
      - name: commit & Push changes ğŸ’¾
        run: |
          # Stage the file, commit and push
          git pull
          git add temp/podcasts_palettes_ner-4
          git commit -m "updated podcast group-4"
          git push origin dist
  wrap-up:
    needs:
      - group-0
      - group-1
      - group-2
      - group-3
      - group-4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Use Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.POD_DATA_GEN }}
      - name: Pull Changes ğŸ’¾
        run: git pull
      - name: prepare
        run: |
          npm install
          npx tsc
          mkdir dist
          mkdir podcasts
          mkdir dist/.github
          mkdir dist/.github/workflows
          cp LICENSE.txt dist/LICENSE.txt
          cp ReadMe.md dist/ReadMe.md
          node out/lib/wrap-up.js
          cp -r podcasts dist/podcasts
          cp .github/workflows/release.yml dist/.github/workflows/release.yml
          rm -rf temp
      - name: Verify Changed files ğŸ’
        uses: tj-actions/verify-changed-files@v8.3
        id: verify-changed-files
        with:
          files: |
            dist
      - name: Deploy ğŸ’¾
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.POD_DATA_GEN }}
